### ISSUE TITLE
Slots?

### ISSUE THREAD

**Issue by zaceno** [picodom/picodom#11]
Vue components have this feature: https://vuejs.org/v2/guide/components.html#Named-Slots Seems like this feature is possible in React as well, albeit by plugging in some third party components

Now I wouldn't say this is a crictical feature exactly, but it makes layout-components a bit more readable. I haven't given it very much thought, but it seems like it's not possible with picodom today to create "slotted" layout components in this way. I think it would require some sort of magic in `h` to be possible.

Has anyone considered this? Any ideas as to how this could work?

**Comment by jbucaran** [comment]
> @zaceno Now I wouldn't say this is a crictical feature exactly, but it makes layout-components a bit more readable. 

What are layout components? And how do they become more readable? 

Can you show me some code? :)

**Comment by zaceno** [comment]
Oh I meant to say: it makes *using* layout components more readable. A layout component (I may have just made up that term) is a component meant to wrap multiple groups of children, in different places.

The following works today:

```
const AppLayout = ({otherProps, leftChildren, topChildren, mainChildren}, children) =>
  <div class="layout-container">
    <div class="layout-left">{leftChildren}</div>
    <div class="layout-right">
      <div class="layout-top">{topChildren}</div>
      <div class="layout-main">{mainChildren}</div>
    </div>
  </div>
```

... and then you might use it like this:

```
const MainView = _ => {
  const leftChildren = [
    DocumentBrowser({current: getCurrentDocumentId()}),
    Advertisement({url: getAdvertiserURL()})
  ]

  const topChildren = [
    DocumentTools({document: getCurrentDocument()),
    AccountMenu({user: getUserInfo()})
  ]

  const mainChildren = [
    DocumentEditor({document: getCurrentDocument()})
  ]

  return AppLayout({leftChildren, topChildren, mainChildren}
}
```

With the concepts of slots, maybe the layout component could look the same, but have the following signature instead:

```
const AppLayout(otherProps, {leftChildren, topChildren, mainChildren}) => ...
```

And the `MainView` could perhaps look like this: 

```
const MainView = _ =>
  <AppLayout>
    <slot name="leftChildren">
        <DocumentBrowser current={getCurrentDocumentId()} />
        <Advertisement url={getAdvertiserURL()} />
    </slot>
    <slot name="topChildren">
        <DocumentTools document={getCurrentDocument()} />
        <AccountMenu use={getUserInfo()} />
    </slot>
    <slot name="mainChildren>
        <DocumentEditor document={getCurrentDocument()} />
    </slot>
  </AppLayout>
```

I'll be the first to admit that the advantage doesn't look very significant, but perhaps there are more convincing examples out there. I just thought it was an interesting feature to consider.

**Comment by jbucaran** [comment]
@zaceno Can you compare slots to custom tags?

I'm confused about the part where you said:

> ... and then you might use it like this:

... considering we can (and should) use custom tags instead of calling functions like in your example.

- https://github.com/hyperapp/hyperapp/blob/master/docs/custom-tags.md

**Comment by zaceno** [comment]
@jbucaran A custom tag is a function, right, with the following signature: `const MyTag = (props, children) => ...` where children is an *Array* of child-nodes to be inserted somewhere in the custom tag.

What I'm suggesting is to make it possible to pass *multiple* sets of children to a custom tag.  In my suggestion, *children* can be an *Object* with named Arrays, rather than just a single array.

 Again, it's probably not important -- so I don't want to push it I just found it an interesting feature, worth considering. The vue docs I linked to above explain it better than I can anyway.

**Comment by zaceno** [comment]
@jbucaran, If I get what you're saying, you would write my example in the following way:

```

const AppLayoutContainer = (props, children) => <div class="layout-container">{children}</div>
const AppLayoutRight = (props, children) => <div class="layout-right">{children}</div>
const AppLayoutLeft = (props, children) => <div class="layout-left">{children}</div>
const AppLayoutTop = (props, children) => <div class="layout-top">{children}</div>
const AppLayoutMain = (props, children) => <div class="layout-main">{children}</div>

const MainView = _ => <AppLayoutContainer>
  <AppLayoutLeft>
    <DocumentBrowser document={getCurrentDocumentId()} />
    <Advertisement url={getAdvertiserUrl() } />
  </AppLayoutLeft>
  <AppLayoutRight>
    <AppLayoutTop>
      <DocumentTools document={getCurrentDocument()} />
      <AccountMenu user={getUser()} />
    </AppLayoutTop>
    <AppLayoutMain>
      <DocumentEditor document={getCurrentDocument()} />
    </AppLayoutMain>
  </AppLayoutRight>
</AppLayoutContainer

```

In any layout, there may be structure that is internal to how the layout works, and best not to expose outside it. In this example, such a structure is that the "top" and "main" areas need to be contained in a "right" area. The benefit of "my way" is that the entire layout is contained in a single component, which encapsulates that knowledge.

**Comment by jbucaran** [comment]
@zaceno So, it comes down to

...now:

```
const AppLayoutContainer = (props, children) =>
  <div class="layout-container">{children}</div>

const AppLayoutRight = (props, children) =>
  <div class="layout-right">{children}</div>

const AppLayoutLeft = (props, children) =>
  <div class="layout-left">{children}</div>

const AppLayoutTop = (props, children) =>
  <div class="layout-top">{children}</div>

const AppLayoutMain = (props, children) =>
  <div class="layout-main">{children}</div>

const MainView = _ =>
  <AppLayoutContainer>
    <AppLayoutLeft>
      <DocumentBrowser document={getCurrentDocumentId()} />
      <Advertisement url={getAdvertiserUrl()} />
    </AppLayoutLeft>
    <AppLayoutRight>
      <AppLayoutTop>
        <DocumentTools document={getCurrentDocument()} />
        <AccountMenu user={getUser()} />
      </AppLayoutTop>
      <AppLayoutMain>
        <DocumentEditor document={getCurrentDocument()} />
      </AppLayoutMain>
    </AppLayoutRight>
  </AppLayoutContainer>
```

vs slots / new feature:

```jsx
const AppLayout(otherProps, {leftChildren, topChildren, mainChildren}) => 
  ...

const MainView = _ =>
  <AppLayout>
    <slot name="leftChildren">
        <DocumentBrowser current={getCurrentDocumentId()} />
        <Advertisement url={getAdvertiserURL()} />
    </slot>
    <slot name="topChildren">
        <DocumentTools document={getCurrentDocument()} />
        <AccountMenu use={getUserInfo()} />
    </slot>
    <slot name="mainChildren>
        <DocumentEditor document={getCurrentDocument()} />
    </slot>
  </AppLayout>
```

@zaceno Can you fill in the missing code `AppLayout`?

**Comment by zaceno** [comment]
Yup! Missing code:

```
<div class="layout-container">
    <div class="layout-left">{leftChildren}</div>
    <div class="layout-right">
      <div class="layout-top">{topChildren}</div>
      <div class="layout-main">{mainChildren}</div>
    </div>
  </div>
```

**Comment by jbucaran** [comment]
@zaceno Thank you! Now, I understand slots more or less. 🙇

**Comment by jbucaran** [comment]
@zaceno Can you please remind me what's wrong with just doing this?

```jsx
const MainView = () =>
  <div class="layout-container">
    <div class="layout-left">
        <DocumentBrowser current={getCurrentDocumentId()} />
        <Advertisement url={getAdvertiserURL()} />
    </div>
    <div class="layout-right">
      <div class="layout-top">
         <DocumentTools document={getCurrentDocument()} />
         <AccountMenu use={getUserInfo()} />
      </div>
      <div class="layout-main">
         <DocumentEditor document={getCurrentDocument()} />
      </div>
    </div>
  </div>
```

**Comment by zaceno** [comment]
@jbucaran, right. Especially if the layout code is even more complex than in my example.

**Comment by zaceno** [comment]
... I'm not coming at it so much from the need to reuse/repeat so much as to keep the layout complexity encapsulated. But yeah, reusability is an important point as well

**Comment by jbucaran** [comment]
@zaceno I haven't investigated how to do slots, but I really don't think I am going to implement this in picodom. 

Do you think this kind of problem could be solved with a function that wraps h without messing with core?

**Comment by zaceno** [comment]
Hm - hadnt thought of the possibility to define your own h that wraps picodoms h, but seems that should work!

Yeah, it seems a bit too much to add anyway, for something that will probably. not be used much. 

Just thought it was kind of neat and wanted to toss the idea out there. But we can certainly close this issue.
