### ISSUE TITLE
Broken link to the API documentation

### ISSUE THREAD

**Issue by smelnicki** [picodom/picodom#12]
Hello! 

Thank you for sharing this. Very cool stuff!

I was poking around the documentation and noticed the [README.md](https://github.com/picodom/picodom/blob/master/docs/README.md) in the docs directory wasn't correctly routing to the [api.md](https://github.com/picodom/picodom/blob/master/docs/api.md) file.

Thought I might help out (albeit in the smallest way possible) while I was browsing around.

**Comment by jbucaran** [comment]
Thanks @smelnicki! 👍
