### ISSUE TITLE
Where are tests? :/

### ISSUE THREAD

**Issue by fccoelho7** [picodom/picodom#16]
First, thank you and congratulations for this amazing library.

We adopted VanilllaJS and it can solve a lot of problems like: bind events in literal dom strings, child replacement right way etc.

BUT

No tests are made and we're afraid to use it. I was seeing the code, and it's really simple. I imagine that tests will be easy. Has any prevision to do it? If you need help, we can relief you.

Regards,
Fabio Carvalho

**Comment by jbucaran** [comment]
Hi @fccoelho7,

You are totally right! Picodom is based on [HyperApp](https://github.com/hyperapp/hyperapp)'s internal virtual-DOM-engine which is tested and has 100% coverage, but that's not an excuse. 🙇

I will work on migrating some of those tests and adapt here very soon and ping you again.

### See Also
- https://github.com/picodom/picodom/issues/3

**Comment by jbucaran** [comment]
@fccoelho7 Added some tests, more on the way. I'll track this in https://github.com/picodom/picodom/issues/3 and when 100% coverage is reached I'll release 0.1.0.

Thanks for your interest! 👋

**Comment by jbucaran** [comment]
@fccoelho7 It took me a while, but I added tests and 100% coverage! 👍
