### ISSUE TITLE
I create a minimalistic component based framework on the top of superfine

### ISSUE THREAD

**Issue by marcodpt** [picodom/picodom#187]
I would like to say thanks to the people involved in this project.
This is in my opinion by far the best frontend vdom javascript framework.
I create this small component approach on the top of this project and I am using it in production with a very happy experience!
[marcodpt/app](https://github.com/marcodpt/app).
Keep your amazing work!

**Comment by jorgebucaran** [comment]
Thank you for sharing @marcodpt! 💯
