### ISSUE TITLE
Redux support

### ISSUE THREAD

**Issue by tracker1** [picodom/picodom#21]
Would be nice to include components for use with redux.  Though I'm unsure if there's a concept of a context, which would be required as a prerequisite.

**Comment by jbucaran** [comment]
Hi @tracker1! I think using redux with picodom should be fairly easy. I can't setup an example right at this moment, but I'll get around it in a couple of days as I think that would be useful to share with everyone.

> Though I'm unsure if there's a concept of a context, which would be required as a prerequisite.

Are you talking about [`<Provider store>`](https://github.com/reactjs/react-redux/blob/master/docs/api.md#provider-store) and "context" as in React's [context](https://facebook.github.io/react/docs/context.html)?

I don't see how that would be required as a prerequisite to use redux together with picodom.

**Comment by tracker1** [comment]
I was referring to `<Provider store>` pretty much whatever `react-redux` offers.. the provider and connect wrapper...  I can work around it for my own use case, but others may find it more useful.

**Comment by jbucaran** [comment]
@tracker1 I want to create a demo to shows how to use redux with picodom. What do you think would make a good example? What should I cover and what do you think I can leave out?

**Comment by tracker1** [comment]
Probably how to provide the store instance through the various components (assuming components in separate files), and how to handle the store's `subscribe` event for (re)rendering/updates on changes.

**Comment by jbucaran** [comment]
@tracker1 It took me a while, but [**here**](https://codepen.io/picodom/pen/eEGGQb0 is the Picodom & Redux example as promised.
