### ISSUE TITLE
(feature) Something like `context` in React

### ISSUE THREAD

**Issue by acstll** [picodom/picodom#26]
Would it be possible to have something like `context` in React?

An object that you could set once on initialisation (in a custom `render` function at the top of your app) and then somehow access it later down in the component tree?

It'd be mostly for convenience, since I'm already passing an object (I think you call it `data`) down, and get my state from it.

I'd like to build something similar to `react-router` to be used with this library.

What do you think? is this even possible? a stupid idea?

**Comment by jbucaran** [comment]
> @acstll What do you think? is this even possible? a stupid idea?

Cool idea. Picodom, unlike hyperapp is only the patch and vnode factory, so I believe you should be able to accomplish almost anything you want by building on top of those two functions.

> An object that you could set once on initialisation (in a custom render function at the top of your app) and then somehow access it later down in the component tree?

Sounds like you already laid out some of the implementation details. How hard could it be to write this render function? 🤔😄

**Comment by acstll** [comment]
After thinking about it for a bit, I believe I'm talking about a custom `h` function.

```js
let context

export function setContext (x) {
  context = x
}
export function h () {
  // ...
}
```

This `h` function would keep a reference to this "context" object and either merge it everytime into `data`, [here](https://github.com/picodom/picodom/blob/master/src/h.js#L28), or pass it as a third argument to components, [here](https://github.com/picodom/picodom/blob/master/src/h.js#L31).

[As a side note, I'm alreay using `picodom` successfully in a tiny app as part of a bigger website. I'm liking it a lot]

**Comment by jbucaran** [comment]
> @acstll  I believe I'm talking about a custom h function.

 Okay, that definitely sounds like a [functor or HOF](https://www.wikiwand.com/en/Higher-order_function). I am not an expert on the terminology, so I had to look that up to make sure, but my understanding is that you would create a function that takes `h` as an argument and returns a new `h'` function that has the built-in technology you need.

**Comment by acstll** [comment]
Ok, HOF sounds familiar to me because of React ([HOC](https://facebook.github.io/react/docs/higher-order-components.html)), but functor does not, haha (I'm no expert either). I think that's one way to do it. I'm going to try that out and let you know how it goes. (Thanks!)

**Comment by jbucaran** [comment]
@acstll Thanks for bringing this up! I'll leave this open for a while.

@ngryman @zaceno Do you have any feedback?

**Comment by zaceno** [comment]
@jbucaran @acstll I think it sounds like a very cool idea, and I look forward to seeing it in practice! 🙏

**Comment by acstll** [comment]
I did something that could be it. It's not something "on top" of picodom as @jbucaran first suggested, but "in it", here's a PR #27

It's so simple that it's a bit scary, haha. I'd love to know your thoughts.

**Comment by jbucaran** [comment]
Closing as wontfix. #27
