### ISSUE TITLE
Selection doesn't set properly on newly created <select> element

### ISSUE THREAD

**Issue by t-kinoshita** [picodom/picodom#29]
in `createElement`, `setData` goes first, then run `appendChild`.

This prevents `<select>` from setting `value`, in the time of `setData` there are no child `<option>`s, so no selection was made.

Any problems for reversing the order of `setData` and `appendChild` ?

**Comment by JorgeBucaran** [comment]
@t-kinoshita Do you have a demo that demonstrates the problem? 🤔

**Comment by t-kinoshita** [comment]
I created [Codepen](https://codepen.io/anon/pen/EwyNmx?editors=1111) reproducing the issue.

All selects should select 1, but only new select is not the case (top 0 is shown).

**Comment by JorgeBucaran** [comment]
@t-kinoshita You found a bug! Would you like to send me a PR? 💪 

The fix appears to be as simple as reversing the order where setData and appendChild are called just as you said. I can't think of a problem right now and tests pass too. 💯

This also affects [hyperapp](https://github.com/hyperapp/hyperapp).

**Comment by infinnie** [comment]
In the initialization phase, set the `checked` attribute to the `option`s instead.

**Comment by JorgeBucaran** [comment]
@infinnie What do you mean? 🤔

**Comment by infinnie** [comment]
```jsx
<select class="select panel__select">
    <option selected={inUse} value="1">In use</option>
    <option selected={!inUse} value="0">Stopped</option>
</select>
```

**Comment by JorgeBucaran** [comment]
@infinnie You mean this is not a bug?

**Comment by infinnie** [comment]
@JorgeBucaran I mean there is possibility to work around it.

**Comment by JorgeBucaran** [comment]
@infinnie Thanks, that clarifies it. :)

**Comment by acstll** [comment]
@JorgeBucaran wouldn't it be a good idea to try and create a failing test before merging the fix? that would document the change better and avoid regressions in the future?

**Comment by JorgeBucaran** [comment]
@acstll That sounds smart. I left @t-kinoshita a comment on the PR.
