### ISSUE TITLE
Add tests.

### ISSUE THREAD

**Issue by jbucaran** [picodom/picodom#3]
Add tests in test.js. 

- [x] Choose a test framework jest
- [x] Test `h.js`
- [ ] Test `patch.js`
  - [ ] Test individual functions.

**Comment by zaceno** [comment]
I've been wanting to use https://github.com/avajs/ava/blob/master/readme.md for a work project but failed to make the tests work in parallel, so I gave up. But for a project like picodom it ought to work very well (and make the tests run very fast)
