### ISSUE TITLE
Update Redux example codepen

### ISSUE THREAD

**Issue by arturi** [picodom/picodom#33]
Picodom is real nice, thank you for your work!

Due to `1.0.0` API change:
> you don't need to keep track of the patched element since we are able to infer it based on the supplied container

the `createRenderer` method in the [Redux example Codepen](https://codepen.io/picodom/pen/eEGGQb) should be changed, if I’m not mistaken, to:

```js
function createRenderer(view, store) {
  let element
  return () => {
    patch(element, (element = view(store)))
  }
}
```

**Comment by JorgeBucaran** [comment]
Fixity fixed. Thanks! 👋
