### ISSUE TITLE
Add JSX support for Typescript

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#34]
With the right declarations in the d.ts file, we should be able to compile directly to h() calls from Typescript, without an additional Babel transform after compiling - as well as getting type-safety and IDE support for JSX expressions in Typescript.

I found clues [here](https://github.com/Microsoft/TypeScript/issues/13402#issuecomment-323623043) and supposedly Snabbdom has this feature.

I will likely experiment with this myself soon, and will post results here if I make any progress :-)

**Comment by andrewiggins** [comment]
@mindplay-dk #19 adds JSX support. Let me know if works for you.

**Comment by mindplay-dk** [comment]
@andrewiggins this looks great! you've done all the hard work :-)

How do I use it? Can you provide the correct `tsconfig.json` settings and a simple example please? (this should probably go in the documentation somewhere, too?)

**Comment by andrewiggins** [comment]
The tests [h.test.tsx](https://github.com/andrewiggins/picodom/blob/be1279b4568b4869a2b80fc14f8a820e9f6a0222/test/typings/h.test.tsx) and [patch.test.tsx](https://github.com/andrewiggins/picodom/blob/be1279b4568b4869a2b80fc14f8a820e9f6a0222/test/typings/patch.test.tsx) provide an example of how to use the typings and the test [tsconfig.json](https://github.com/andrewiggins/picodom/blob/be1279b4568b4869a2b80fc14f8a820e9f6a0222/test/typings/tsconfig.json) shows an example of a tsconfig.json that compiles those files.

Once #19 completes, we can add a reference to the test files as examples for using the TypeScript definitions in the documentation somewhere
