### ISSUE TITLE
Add test for picodom.d.ts (add working type-declarations)

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#35]
The d.ts file appears to be full of errors.

The `VNode<Data>` interface doesn't use the `Data` type-argument, and references a type `Props` which doesn't seem to exist.

The rest-param `children` in `Component<Props>` isn't valid - rest arguments must have an array-type. Same for `h<Props>`.

The `patch` function was declared with a default argument value `document.body`, which I don't think you can do in interfaces.

Is the d.ts file just a draft or something?

A test for the type-declarations probably ought to be added.

**Comment by JorgeBucaran** [comment]
@mindplay-dk It was supposed to be the real deal! 😉 

Maybe @pspeter3 @andrewiggins @swizz know.

**Comment by andrewiggins** [comment]
@mindplay-dk Take a look at my PR #19 on improving the types and adding tests and let me know if i missed anything.

**Comment by andrewiggins** [comment]
I've been slow on getting that PR completed - sorry for the delay 😞

**Comment by pspeter3** [comment]
Yeah, this was more of a draft before I got more involved with the Hyperapp project. I will look at PR #19
