### ISSUE TITLE
what's the cb argument to patch() ?

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#38]
The `patch()` function accepts a fourth argument, `cb`, which appears to be unused and gets immediately overwritten in a while-loop inside the function.

This argument also doesn't figure in documentation or in the Typescript declaration file.

What's it for?

**Comment by JorgeBucaran** [comment]
@mindplay-dk It's not in the declarations file because it's for private use. It's just a local variable.

https://github.com/picodom/picodom/blob/ca5aa34026d5ef366b0a411e550cb976c4589370/src/patch.js#L13-L16

We could `var cb` right above the `while` loop just as well.
