### ISSUE TITLE
Transactional/scheduled DOM updates

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#39]
I completely understand if this is out of scope for this library - I'm mostly asking to make sure it's been considered and deliberately omitted.

If you're familiar with [fastdom](https://github.com/wilsonpage/fastdom), scheduled/transactional DOM updates eliminate DOM thrashing, as do most modern libraries/frameworks. I'm not proposing we use this library, I'm merely wondering if this is common enough that you'd want the library to cover that.

I understand that there's nothing preventing you from implementing this library or the technique in your own application or framework - but unless it's something you plan for and design around, you're more likely than not to end up creating something that does thrash the DOM, and maybe that's not a desirable "default", if we can design a simple/solid solution around it?

I think it's worth considering, though as said, I completely understand if this is out of scope.

**Comment by JorgeBucaran** [comment]
Sounds interesting, I'll try to look into it when I have time! Thanks for bringing this up.

**Comment by mindplay-dk** [comment]
Here's the solution I'm currently using.

```js
import { VNode, patch } from "picodom";

/**
 * Bind a given target element to a model instance and a view-function.
 * 
 * An update-function is returned - when called, this will present the model instance
 * to the view, and update the target element to which the view/model was bound.
 */
export default function bind<TModel>(target: HTMLElement, model: TModel, view: { (model: TModel): VNode<{}> }) {
    let oldNode: VNode<{}>;
    let scheduled = false;

    return function update() {
        if (!scheduled) {
            scheduled = true;
            
            requestAnimationFrame(() => {
                let newNode = view(model);

                patch(target, oldNode, newNode);

                oldNode = newNode;

                scheduled = false;
           });
        }
    }
}
```

It's pretty simple, just tracks whether an update has already been scheduled, and defers it - this lets me make numerous calls to actions that call an `update()` function without clobbering the DOM.

In it's current form, this likely belongs in a framework and not in picodom itself.

**Comment by JorgeBucaran** [comment]
Yes, this looks very much like framework material to me. Also, there was a clear misunderstanding (from my part) as I thought you meant something completely different with this issue.

The solution you posted above is similar to what we were doing in Hyperapp, but this has now changed to using setTimeout, because rAF causes issues (by design) with inactive tabs / calls are throttled it seems.

**Comment by mindplay-dk** [comment]
Maybe this doesn't belong in this library at all? Should we just close the issue?

**Comment by JorgeBucaran** [comment]
@mindplay-dk Yep, definitely not something we should force into users by default. But we could have a `picothrottle` (or else if you have a better name) library. Just thinking out loud. 🤔😉
