### ISSUE TITLE
Add @next tag

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#42]
Could we have a [dist-tag](https://docs.npmjs.com/cli/dist-tag) for `picodom@next` please?

So we can more easily help beta-test the next major version, updating examples, etc. before release.

**Comment by JorgeBucaran** [comment]
@mindplay-dk Can you describe the process to make this possible?

**Comment by mindplay-dk** [comment]
The link seems to explain it? I don't know npm very well tbh.

**Comment by JorgeBucaran** [comment]
I put about an hour, but couldn't make this work. Maybe my understanding of what should happen is not what the dist-tag feature is about.

I tried adding a `next` tag this way:

```
npm dist-tag add picodom/picodom@1.0.3 next
```

I know I still haven't published 1.0.3, so I wonder if that's the reason it fails. But if I add a version that's already published, then what's the point of this feature? Is it just an alias?

I don't think it's just about aliasing, from their docs:

> **PURPOSE**

>Tags can be used to provide an alias instead of version numbers.
>
>For example, a project might choose to have multiple streams of development and use a different tag for each stream, e.g., stable, beta, dev, canary.
>
>By default, the latest tag is used by npm to identify the current version of a package, and npm install <pkg> (without any @<version> or @<tag> specifier) installs the latest tag. Typically, projects only use the latest tag for stable release versions, and use other tags for unstable versions such as prereleases.
>
>The next tag is used by some projects to identify the upcoming version.
>
>By default, other than latest, no tag has any special significance to npm itself.

**Comment by JorgeBucaran** [comment]
@mindplay-dk Okay, it worked, finally. **No need** to use dist-tag, unless I

**Comment by JorgeBucaran** [comment]
@mindplay-dk I finally figured it out. I didn't need to use dist-tag. What one needs to do is is:

- Bump the package version. I bumped it to 2.0.0.
- git add and commit your stuff.
- npm publish **--tag next**

This will publish a new version of your package that can only be installed with `npm i picodom@next`.

That's all. The dist-tag command is there to help you manage your published tags, listing them, adding or removing them, not publishing.

<img width="1280" alt="screen shot 2017-11-09 at 12 38 26" src="https://user-images.githubusercontent.com/56996/32587442-acd3deb0-c54b-11e7-877a-a586dcf636bc.png">

**Comment by mindplay-dk** [comment]
Oh, cool! Thanks for explaining it :-)

**Comment by acstll** [comment]
@JorgeBucaran I'm not completely sure, but I think the way to do this is by having a `2.0` branch (or `next` branch) where you work on this next version and then publish using `--tag next`, as you did. 

I think now you can't continue to work on 1.x on master and publish further updates… :(

**Comment by JorgeBucaran** [comment]
@acstll You are right Arturo. 😆  

Thank for helping me understand the final piece of the puzzle, we'll do it right from now on (after 2.0.0).

**Comment by acstll** [comment]
@JorgeBucaran no problem. Open source FTW 😊
