### ISSUE TITLE
Related project: dot-dom

### ISSUE THREAD

**Issue by styfle** [picodom/picodom#43]
I just found picodom and I'm curious how it compares to [wavesoft/dot-dom]( https://github.com/wavesoft/dot-dom).

Are the project goals the same?
And could these projects share ideas?

**Comment by mindplay-dk** [comment]
A couple of differences I could spot:

1. This library synchronizes VNode state directly to DOM, whereas pico diffs two VNodes and applies the changes - this approach (for one) allows third-party JS scripts to participate in maintaining portions of the DOM without conflict.

2. Pico offers lifecycle events - this doesn't seem to (?)

3. Pico works on more current browsers.

4. This library is aggressively minified, where pico prioritizes readable code over minimal byte savings.

Surely this demonstrates that pico could be made smaller, though personally I don't really see the point - a single IP network packet on a typical  connection is 1400-1500 bytes, so you're not really saving anything.

Just my point of view, but I really think pico has all the right priorities - that is to say, they definitely align with mine :-)

**Comment by mindplay-dk** [comment]
Oh, and it doesn't appear to support keyed updates either - these can be really important for things like tabular forms.

**Comment by styfle** [comment]
Thanks!

**Comment by JorgeBucaran** [comment]
Hi @styfle. I knew about dot-dom from before. The reason dot-dom manages to be even smaller than picodom is because they are using advanced features like Symbols, Proxies, do not support JSX and more importantly, lack keyed updates. Keyed updates is what makes the bulk of the VDOM.

Having said that, they did a great job!
