### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by acstll** [picodom/picodom#44]
I'm getting a `SyntaxError: Unexpected token import` error for all 4 suites.

This seems to be Jest not finding some `babel` configuration, [see here](https://stackoverflow.com/questions/41725796/jest-test-suite-failed-to-run-syntaxerror-unexpected-token-import).

I see there's no .babelrc file, just this: https://github.com/picodom/picodom/blob/master/package.json#L30

Any ideas?

(I just do `npm test` with node version `8.9.0`.)

**Comment by JorgeBucaran** [comment]
@acstll Did you run `npm i` on the root directory?

**Comment by acstll** [comment]
> @acstll Did you run npm i on the root directory?

yep.

Do you have any global babel configuration? I don't know if such thing exists…

**Comment by JorgeBucaran** [comment]
No, there is no global babel configuration. Maybe it's your node version?

**Comment by acstll** [comment]
Ok, got it working with node 6, maybe this is an issue with Jest?

**Comment by JorgeBucaran** [comment]
@acstll What node version were you using?

**Comment by acstll** [comment]
> @acstll What node version were you using?
8.9.0

(latest LTS is 8.9.1)

**Comment by JorgeBucaran** [comment]
@acstll And tests failed on 8.9.0? That's my version too. 😕

**Comment by JorgeBucaran** [comment]
<img width="1280" alt="screen shot 2017-11-10 at 0 23 01" src="https://user-images.githubusercontent.com/56996/32613120-565dc53e-c5ad-11e7-958f-1635f8633a90.png">

**Comment by acstll** [comment]
Interesting. I will try and reinstall 8.9.x to see if that fixes it (I'm also using `npm` not `yarn`). Thanks for your help :)

**Comment by JorgeBucaran** [comment]
FYI `npm run test` was OK too.
