### ISSUE TITLE
Avoiding the extra wrapper tag?

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#45]
I wonder if there's any way to avoid an extra wrapper tag?

What I mean is, let's say I have a page with a div with id=app on the page - I use this as the root, but my JSX is going to start with a root wrapper of its own, so now I'm two levels deep already.

Could this be addressed somehow? Not easily, I guess - since diff is done on VNodes, we can't directly diff against an existing root element.

I'm a bit bothered by the fact that the implementation strategy dictates the HTML structure. What if I'm adding to a project with pre-existing CSS that doesn't fit? What if my CSS/HTML designer guy is opinionated? ;-)

I don't know, maybe it's not worth worrying about?

It was possible with hyperHTML, which is why I'm noticing the difference - it didn't enforce a single root node, and diffs directly against the DOM. (which is not an approach I'd suggest.)

**Comment by JorgeBucaran** [comment]
@mindplay-dk Can you show the code with the current result body and the result you want?

**Comment by mindplay-dk** [comment]
Uhm, well, let's say I have a static page with some kind of layout.

```html
<body>
    <div class="header">.....</div>
    <div id="fancy_app"></div>
    <div class="footer">.....</div>
</body>
```

And then something like:

```js
import { patch, h } from "picodom";

function view() {
    return
    <div class="woot">
        <h1>Boom!</h1>
    </div>
}

patch(document.getElementById("fancy_app", {}, view());
```

Now I end up with:

```html
<body>
    <div class="header">.....</div>
    <div id="fancy_app">
        <div class="woot">
            <h1>Boom!</h1>
        </div>
    </div>
    <div class="footer">.....</div>
</body>
```

So now, the top-level node of the actual view is `div.woot`, but it's wrapped in `div#fancy_app` - one of those two would have likely been enough, but... I guess JSX syntax forces you to always return a single parent node, and you have to have another reserved node to render into, whether that's `body` or something else...

I don't know, maybe it's no big deal? I only brought it up because hyperHTML, using template strings, allowed me to render multiple nodes into a target container - but I guess maybe the limitation here is actually JSX syntax itself?

**Comment by mindplay-dk** [comment]
Good point about the document body, yeah, that wouldn't even make any sense.

In my mind, I'm trying to turn this into a good thing - the fact that every view or component has precisely one root node actually makes the whole app (and framework) much simpler and easier to reason about. Maybe "fixing" this isn't even a good idea?

**Comment by JorgeBucaran** [comment]
@mindplay-dk This is one of the reasons the container was optional. So, that default behavior would be append to document.body without wrapper elements.

**Comment by mindplay-dk** [comment]
I think there's nothing actionable here, so I'm closing this issue.
