### ISSUE TITLE
Typescript: add default type-argument to VNode

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#47]
Having to explicitly type-hint node arguments as `Node<{}>` gets tedious doesn't read well.

Can we make it the default?

```ts
export interface VNode<Props = {}> {
  type: string
  props?: Props
  children: Array<VNode<{}> | string>
}
```

This way you can type-hint as just `Node`.

We can then clean up all the other `VNode<{}>` type-hints in the declarations file as well.

**Comment by JorgeBucaran** [comment]
@mindplay-dk I am not sure what you mean. Is this about making `h(type, children)` possible?

**Comment by mindplay-dk** [comment]
No, it's just about setting a default `{}` type argument for `VNode`, so that you don't have to specify it explicitly every time you're trying to type-hint something - with `Props = {}` the type-argument defaults to `{}`, so that type-hinting as `VNode` without type-arguments means the same as `VNode<{}>` does now.

**Comment by JorgeBucaran** [comment]
Well, sure there. This is non-breaking yeah?

**Comment by mindplay-dk** [comment]
Yep :-)
