### ISSUE TITLE
Broken source-maps in `@next`?

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#48]
Looks like the source-map has gone bonkers in the 2.0 beta?

![source-maps](https://user-images.githubusercontent.com/103348/32658410-2ad5ed2a-c61a-11e7-9a72-00363277edf6.gif)

It thinks `node` is undefined, and somehow `node.type` is a `VNode`, *in the same expression??*

And this is a trivial example like `patch(root, null, <div>LALALA</div>)`, which doesn't work anymore...

```
patch.js:117 Uncaught TypeError: Cannot read property 'type' of null
    at l (patch.js:117)
    at Object.n [as patch] (patch.js:4)
    at window.setTimeout (media.tsx:61)
```

I mean, all the tests were passing, so what the....?

**Comment by JorgeBucaran** [comment]
@mindplay-dk What do you call broken exactly? I can see the source of patchElement, that's all it is AFAIK.

https://github.com/picodom/picodom/blob/ef045b03e7bb43174afbe66a7a34358cef027d27/package.json#L22-L24

**Comment by mindplay-dk** [comment]
Look at the screen recording? If that's not the source map, Chrome must be severely broken??

**Comment by JorgeBucaran** [comment]
@mindplay-dk I think sourcemaps are working fine, or at least there's nothing we can do about it. 

<img width="1218" alt="screen shot 2017-11-11 at 3 44 27" src="https://user-images.githubusercontent.com/56996/32673474-b6ba4c8c-c692-11e7-844c-24deba060a83.png">

**Comment by JorgeBucaran** [comment]
I am going to close here since I feel there's nothing I can do, but if you have any ideas, please do let me know.

**Comment by mindplay-dk** [comment]
Weird. Maybe this is a Chrome bug after all, I have seen something similar happening on another project lately, but always assumed it was due to mismatched source maps...
