### ISSUE TITLE
setElementProp removes falsy attribute values

### ISSUE THREAD

**Issue by maxholman** [picodom/picodom#49]
In a recent `hyperapp` issue [Updating children props dynamically ignores "0" #419](https://github.com/hyperapp/hyperapp/issues/419) `setElementProp` behaviour was improved when dealing with falsy values.

Will `picodom` be getting the same logic update?

My specific use case is attempting `<option value="">Not applicable</a>` but `picodom` removes my value attribute and the browser subsequently considers the selected value to be `"Not applicable"`

Contrived example: https://codepen.io/maxholman/pen/vWmgPa

**Comment by JorgeBucaran** [comment]
@maxholman Yes, it totally should. The same part of the code could be easily ported over. If anyone wants to me beat me to it, feel free to send me a PR, otherwise I may be able to work on this over the next week. 

Thanks! 💯

**Comment by maxholman** [comment]
I'll put a PR together :+1:
