### ISSUE TITLE
Enhance lifecycle events.

### ISSUE THREAD

**Issue by jbucaran** [picodom/picodom#5]
/cc @ngryman

**Comment by ngryman** [comment]
I guess we are speaking about hooks, which produce internal side-effects, as opposed to events.

Well basically, you could expose the same hooks as Snabbdom: https://github.com/snabbdom/snabbdom#overview

What do you think?

**Comment by jbucaran** [comment]
Nice. Snabbdom can teach us a lot here, but I'd like to keep things as simple as possible too.

**Comment by jbucaran** [comment]
@ngryman Your ideas are intriguing to me and I wish to know more.

**Comment by ngryman** [comment]
It depends on the degree of control you want to give to users.

If it's just reacting to lifecycle events, I guess current implementation is enough.

If you want to give more control on internal stuff (IoC), the above propositions could allow users to potentially:
 - mutate the vdom tree: custom tags/dsl, higher order components, ...
 - prune a part of the tree during diffing/patching: optimization
 - implement things not included out-of-the-box: custom attributes, DOM specificities/inconsistencies, ...
 - and whatever could be useful: auth, logging, DI, whatever ...

The only "API" vdom-based frameworks expose is `h` (and for some the concept of components) which allows to do pretty much everything.
But exposing the internals and develop a plugin ecosystem could bring new ways of handling things, transparently.

---

Let's give some messy examples.

Recently I've been using higher order components a lot. They are really useful. But I have the feeling that I'm using a rendering framework to implement behavioral stuff, which doesn't feel quite right. Plus it clutters the code and the components tree.
If a framework/plugin allowed me to implemented the same thing transparently it would be awesome.

Let's say I want to hide a component if a user is not authenticated. Usually I create a HOC for that which wraps another component and display it only if the user is authenticated.
If I had access to the internals, I would be able to do this in a real simple way:

```js
// Returning `false` prunes the the whole and its children
const authenticated = (state) => () => state.loggedIn

const FriendsList = (state) => (
  <ul class="friends-list" oncreate={authenticated(state)}>
    <!-- ... -->
  </ul>
)
```

And if I want this to be handled transparently, I could automate the process for every tag having the `authenticated` attribute and hook to the root:

```js
const authenticated = (state) => (element, node) => {
  // walk the vdom tree and decorate tags with the `authenticated` attribute
  return node
}

const App = (state) => (
  <div id="#app" oncreate={authenticated(state)}>
    <FriendList authenticated />
  </div>
)
```

Another example would be a loader that is displayed while the data is fetched.

**On the component itself**:

```js
const loader = (data) => (element, node) => (
  data.length === 0
    ? <div>Loading...</div>
    : node
)

const FriendsList = (state) =>  (
  <ul class="friends-list" oncreate={loader(state.friends)} onupdate={loader(state.friends)}>
    <!-- ... -->
  </ul>
)
```

**Or globally**:

```js
const loader = (state) => (element, node) => {
  // walk the vdom tree and decorate tags with the `loader` attribute
  return node
}

const App = (state) => (
  <div id="#app" oncreate={loader(state)}>
    <FriendList loader />
  </div>
)
```

That's really scratching what could be done with just some modifications to the current API.

**Comment by jbucaran** [comment]
@ngryman Returning false in oncreate skips creating the element and its children?

**Comment by ngryman** [comment]
@jbucaran I guess so, until it finally returns nothing (`null` or `undefined`) or a node.

**Comment by jbucaran** [comment]
Going to close here as I have settled on the VDOM events API and like it this way! Thanks @ngryman! 👍
