### ISSUE TITLE
use patch nested

### ISSUE THREAD

**Issue by genofire** [picodom/picodom#51]
Hi,
i would like to use the command `patch` nested, so patch did not render the complete website dom.

Example:
```js
const messages = ['hello', 'spam'];
function renderMsg (msg) {
  return V.h('div', {'class': 'ui floating message',
    'onclick': () => {
      if (messages.indexOf(msg) !== -1) {
        messages.splice(messages.indexOf(msg), 1);
        renderNotifications();
      }
  }},msg);
}
function renderNotifications(main) {
  V.patch(el, el = V.h('div', {'class': 'notifications'}, messages.map(renderMsg)), main);
}

let notifyEL = V.h('div');
renderNotifications(notifyEL);
V.patch(body, body=V.h('div',null,notifyEL),document.body);
```
Is this on any way possible?

**Comment by JorgeBucaran** [comment]
Hi @genofire! I am afraid I don't really understand what you are trying to do, so I can't help you.

Can you create a example with a demo, CodePen/JSFiddle, etc?

**Comment by JorgeBucaran** [comment]
@genofire Maybe you didn't find out about the API change?

```js
const element = patch(
  parent,  // parent HTMLElement to be patched
  oldNode, // the old VNode
  newNode  // the new VNode
)
```

So, try:


```js
V.patch(
  main,
  el, 
  el = V.h('div', {'class': 'notifications'}, messages.map(renderMsg))
)
```

**Comment by genofire** [comment]
(that has already cost me a hour - no)

i would like a VNode as parent or use a HTMLElement as h children (in a VNode).

**Comment by JorgeBucaran** [comment]
> @genofire i would like a VNode as parent or use a HTMLElement as h children (in a VNode).

That's not possible, the `parent` must be of type `HTMLElement` and `oldNode`, `newNode` must be of type [VNode](https://github.com/picodom/picodom/blob/ef045b03e7bb43174afbe66a7a34358cef027d27/picodom.d.ts#L3) both.

**Comment by mindplay-dk** [comment]
> i would like a VNode as parent or use a HTMLElement as h children

@genofire the reason `oldNode` and `newNode` must both be `VNode`, is because (1) we can more accurately patch the DOM according to *your* view's new/old state, which means you can safely use third-party JS that appends/modifies nodes, e.g. hooked in via `oncreate`/`ondestroy`, and (2) patching against actual DOM nodes adds a substantial layer of complexity, because working with the DOM API is so much more verbose than working with the simple, flat `VNode` interface.

**Comment by JorgeBucaran** [comment]
Closing as there's nothing actionable here.
