### ISSUE TITLE
questions about setElementProp()

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#54]
I've been studying the source code closely, and have a few questions regarding `setElementProp()`:

1. How or why is it useful/relevant to set a single prop? Aren't props always a set? If so, shouldn't this be `setElementProps()` (plural) to avoid the loop and function-call overhead at every call site?

2. Regarding setting of properties (not attributes), this line:
    ```js
    try {
      element[name] = null == value ? "" : value
    } catch (_) {}
    ```

    Why the null (ish) check and defaulting to empty string? It's not a given that the property being set is even a string property. It's also not a given that I wouldn't want to set a property to null. These are object-properties, but they seem to get treated like attribute-values?

    And why the `catch`? Capturing a stack-trace is expensive, isn't it? Might be cleaner to check for existence with `name in element` prior to setting?

3. Regarding the overall logic:
    ```js
    try {
      element[name] = null == value ? "" : value
    } catch (_) {}

    if (typeof value !== "function") {
      if (null == value || false === value) {
        element.removeAttribute(name)
      } else {
        element.setAttribute(name, value === true ? "" : value)
      }
    }
    ```

    Aren't we doing double duty here? First setting as property-value, then setting as attribute-value. If we had the property-check (above) we'd could make these mutually exclusive, so properties take precedence over attributes, and so we don't do double assignments - probably more correct and better for performance?

For example, right now, if I do something like `<div innerHTML={content}>`, I will end up with the same HTML injected as an attribute-value.

**Comment by JorgeBucaran** [comment]
1. Sure!
2. To avoid converting `null` or `undefined` to a string and the try/catch is to avoid edge cases like read only props.
3. I am open to simplifying that piece of logic, even if it costs a few more bytes, but not a lot.

**Comment by JorgeBucaran** [comment]
> @mindplay-dk Capturing a stack-trace is expensive, isn't it?  

I remember thinking the same, but it turned out that using try/catch yielded better/faster performance when using js-framework-benchmarks.

**Comment by mindplay-dk** [comment]
> To avoid converting `null` or `undefined` to a string

That matters for attributes - but these are properties?

> the try/catch is to avoid edge cases like read only props

Figured as much, though, frankly, if I make the mistake of trying to set a read-only prop, isn't it simpler and more helpful to get an error and stack-trace, so I can know I've done something wrong?

I'm not a big fan of silencing errors when the developer is doing something wrong.

Are there any other edge-cases for this to handle?

**Comment by JorgeBucaran** [comment]
@mindplay-dk That was one example, there were more errors, but unfortunately I didn't keep a list of what they were. FWIW, Preact uses a similar strategy.

> That matters for attributes - but these are properties?

How do you know which one is a property and which one is an attribute without including a big whitelist?

**Comment by JorgeBucaran** [comment]
@mindplay-dk I remember one particular error caused by a Chrome bug in how it handles some props of the [Selection](https://developer.mozilla.org/en-US/docs/Web/API/Selection) API.

**Comment by mindplay-dk** [comment]
> How do you know which one is a property and which one is an attribute without including a big whitelist?

`name in element` will tell you if it's a property - this being JSX, we're binding JS values, so it makes sense for properties to take precedence over attributes.

For example, the `onclick` attribute contains JS source-code, which is totally uninteresting - we have literal functions in a JSX context, so we'd want the `onclick` property.

Am I missing something? :-)

**Comment by JorgeBucaran** [comment]
@mindplay-dk `on` handlers are already handled. 

I think if we could have some code, in the form of a PR, it would be easier to discuss what we want to add to or remove from core. 👍

**Comment by mindplay-dk** [comment]
Okay, well, I attempted the change to `setElementProp`:

```
    if (name in element) {
      element[name] = null == value ? "" : value
    } else if (typeof value !== "function") {
      if (null == value || false === value) {
        element.removeAttribute(name)
      } else {
        element.setAttribute(name, value === true ? "" : value)
      }
    }
```

But it doesn't play nice with things like `value` which exist both as properties and attributes:

```
    Expected value to be (using ===):
      "<input type=\"text\" value=\"\">"
    Received:
      "<input type=\"text\">"
```

That is, it fails the test - I'm fairly certain it would work on a real browser?

But it seems this causes problems with things like `id` as well, which behaves differently - apparently you can *set* it with `el.id = "foo"`, but you can't *remove* it with `el.id = null`, which instead results in the *attribute* being set to `"null"`. Weird inconsistencies here :-/

I also tried factoring `setElementProp()` into `setElementProps()`, but that also doesn't appear to be feasible, because the logic is different at different call-sites - some calls merge the properties, others make two passes, so I don't think we can really factor it that way.

I am concerned that setting actual properties also randomly sets attributes - we're littering the DOM with potential garbage, but I don't have any idea what to do about it at this moment. Or, at least, I can't think of any *simple* way to address this. I'll keep pondering this...

**Comment by JorgeBucaran** [comment]
> @mindplay-dk I am concerned that setting actual properties also randomly sets attributes - we're littering the DOM with potential garbage...

What are some examples of properties we are also setting as attributes, but we shouldn't?

**Comment by mindplay-dk** [comment]
I've opened a new issue for that discussion - I'm closing this one as there's nothing actionable here.
