### ISSUE TITLE
Event handlers have no context?

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#58]
Looks like event-handlers have no `this` context?

For example:

```js
<button onclick={ () => console.log(this) }>Hello</button>
```

It looks like `this` is the number `0`?

I was expected maybe `this` would reference the event target - the `button` element?

(If we address this, it likely needs to be addressed separately for the life-cycle events.)

**Comment by JorgeBucaran** [comment]
@mindplay-dk The event target is `e`:

```jsx
<button onclick={ e => console.log(this) }>Hello</button>
```

Is that not enough?

**Comment by mindplay-dk** [comment]
My point is it's *surprising*, because it's inconsistent with how DOM works, where, normally something like `onclick="console.log(this)"` executes with the element as context.

This would work with practically any other framework or library, right? I think it's natural to expect a meaningful calling context, consistent with normal DOM use.

**Comment by JorgeBucaran** [comment]
@mindplay-dk You got me there! I was not aware that `this` inside event handlers is bound to the event handler. Seriously? 😮

**Comment by mindplay-dk** [comment]
No, it's not bound to the event handler? Not if by that you mean the function that handles the event?

It's bound to the element for which the event occurred - so with plain DOM you could do:

    <div onclick="this.classList.toggle('is-active')">

Which is pretty common.

It would be natural to expect the equivalent to work with JSX:

    <div onclick={ () => this.classList.toggle('is-active') }>

I don't understand how this is at all surprising - these techniques are as old as time itself.

Or at least as old as Netscape ;-)

**Comment by JorgeBucaran** [comment]
@mindplay-dk Hmm, okay then I probably thought something else. I haven't seen this in years. Do you happen to know what React or Preact do here?

**Comment by mindplay-dk** [comment]
In React, you have the `render` method in a `Component` implementation, so event handlers are bound to the `Component` instance. I'm not sure what the context is for stateless components rendering elements into the DOM directly - it can't be a component instance, since there isn't one, but.... (?)

**Comment by JorgeBucaran** [comment]
@mindplay-dk Okay. I think we should not bind `this` to the event instance. In fact, I personally want to discourage use of `this`.

**Comment by mindplay-dk** [comment]
> I think we should not bind `this` to the event instance

Not what I was suggesting - standard DOM handlers are bound to the `Element` instance, e.g. with HTML:

    <button onclick="console.log(this instanceof HTMLElement)">Boom!</button>

Clicking this buttons emits `true` in the console - whereas the corresponding JSX:

    <button onclick={ () => console.log(this instanceof HTMLElement) }>Boom!</button>

Emits `false`.

It would be less surprising if these were consistent, I think.

If you don't agree, let's just close this issue.

**Comment by JorgeBucaran** [comment]
I get it now. You could retrieve the element from the event handler. No, I want to keep this open as I still don't know what to do with this one. For Picodom the "right" way to go would probably be as you suggest.

**Comment by jamen** [comment]
Worth noting that you cannot bind `() => {}` as mentioned:

```js
const foo = () => console.log(this)
foo.call("Hello")
// Not "Hello"
```

Curious if this works with `function () {}`.  But either way, the `event.target` seems to suffice.

**Comment by JorgeBucaran** [comment]
@jamen True, I'd forgotten about that. That means the user would need to pass a normal function to be able to get the Element-bound `this`.

**Comment by mindplay-dk** [comment]
Ugh, yeah, I see.

Man, why does the fat arrow operator even produce a `Function` instance? Neither `bind()` nor `call()` actually works like it does on other `Function` instances - those methods simply don't *work*. JS FTW 🙄 

Oh well. It's not possible, so I suppose we can close this issue?

**Comment by JorgeBucaran** [comment]
~~this~~
