### ISSUE TITLE
Input type=text selection resets.

### ISSUE THREAD

**Issue by acstll** [picodom/picodom#6]
If you type somewhere in the middle of the input field, the cursor jumps to the end.

https://codepen.io/picodom/pen/BRbJpG?editors=0010

**Comment by jbucaran** [comment]
Yes. This is related to: https://github.com/hyperapp/hyperapp/pull/137.

There may be a simpler solution / fix via setElementData.

We can probably learn from Preact here.
- https://github.com/developit/preact/blob/47a85cf8bd4c50b45fa114171a5980fd88cade23/src/dom/index.js#L80

**Comment by jbucaran** [comment]
@acstll ec4d182
