### ISSUE TITLE
RFC: Should we drop built-in core JSX support?

### ISSUE THREAD

**Issue by JorgeBucaran** [picodom/picodom#60]
Should we drop built-in JSX support? Yes or No?

This involves modifying (simplifying really) how hyperapp.h works, by making it monomorphic (single signature) instead of the current implementation that supports multiple varargs (arguments are slow!).

### Pros

- Better performance.
- More liberty in how components are used / instantiated.

### Cons

- No JSX. Or at least not until babel/babel#2034 is resolved.

### Ref

- https://github.com/hyperapp/hyperapp/issues/462

**Comment by JorgeBucaran** [comment]
https://github.com/hyperapp/hyperapp/issues/462

**Comment by zaceno** [comment]
Because picodom has a more general purpose than hyperapp, I think we should keep JSX support for now, regardless of what hyperapp does.

**Comment by mindplay-dk** [comment]
The patch function  isn't much use without virtual DOM nodes.

On the other hand, I already have my own `h` function adding some more functionality, and already considered copying the body of pico's `h` function into it, to avoid doubling the number of function-calls, which doubles the number of stack-frames, affecting memory usage, etc.

I'm honestly not sure.

**Comment by JorgeBucaran** [comment]
@mindplay-dk If you have an alternative to `h()` that performs better or has any improvements I'd honestly love to see it We've gone through so many iterations with that function, that I don't really know what else we could do to make it better.

**Comment by zaceno** [comment]
@mindplay-dk The question is about removing JSX support is not about removing the h-function entirely. Its only this: 

Today, both of these work:

A: `h(props, [vnode1, vnode2, vnode3...])`
B: `h(props, vnode1, vnode2, vnode3....)`

JSX relies on (B), and "dropping JSX support" would mean only (A) would work in the future.

**Comment by mindplay-dk** [comment]
> "dropping JSX support" would mean only (A) would work in the future.

But A isn't even supported at this time, nor by babel or Typescript, is it?

We can't drop B while it's the only thing that works? :-)

**Comment by JorgeBucaran** [comment]
@mindplay-dk AFAIC both A and B are currently supported by the library.

**Comment by mindplay-dk** [comment]
@JorgeBucaran yes, and it sounds like this proposal is about removing B, which is the only one that works?

**Comment by JorgeBucaran** [comment]
@mindplay-dk No. Both A and B work. This proposal is about removing B. 

I want to gather feedback first, this is not really a proposal per se.

> Because  picodom has a more general purpose than hyperapp, I think we should  keep JSX support for now, regardless of what hyperapp does.

I agree with this, so I am not so excited about the idea anymore. 😄
