### ISSUE TITLE
Possibility to calculate diff without applying the changes (patching) to the dom

### ISSUE THREAD

**Issue by cjh9** [picodom/picodom#62]
I would like to calculate the diff between two trees, without patching, because it will be done in a webworker (without access to the DOM). 

Similarly to what is done here: https://github.com/Matt-Esch/virtual-dom
```
var patches = diff(tree, newTree);
rootNode = patch(rootNode, patches);
```
Can this be done in this vdom implementation?

**Comment by JorgeBucaran** [comment]
@cjh9 I haven't explored this idea in picodom because of the size limitation and because there are libraries that already do it, and I am personally more interested in improving the diff algorithm. 

It would be cool, though if you or anyone worked on this as a fork or picodom spin-off. 

https://github.com/hyperapp/hyperapp/issues/216

**Comment by leeoniya** [comment]
from what i remember, the overhead of webworker communication usually erases any perf gains and ends up behind. this may have been before Transferable Objects though, and you'd gain some async properties by doing this, even if not speed.

**Comment by cjh9** [comment]
@leeoniya This is not the case in my case, I'm rendering a huge tree which sometimes blocks the UI (even though the dom-change is very small)

**Comment by leeoniya** [comment]
> a huge tree

can you quantify this? how many DOM nodes?

**Comment by cjh9** [comment]
@leeoniya I'ts a markdown editor that converts to virtual dom, so i'm just testing corner cases with large documents. If printed the document will be ~100 pages (not that it will tell you that much, it ofc depends on the font size etc 😅 ) I haven't calculated the actual number. So then it takes in the order of 0.5s to do the diff + patch + browser render...

**Comment by leeoniya** [comment]
> I haven't calculated the actual number.

open devtools and run `document.querySelectorAll("*").length`

**Comment by cjh9** [comment]
@leeoniya 100102 nodes, numbers in milliseconds:

Markdown 281.75
KATEX 1253
Parse Tree 519 (HTML -> syntax tree)
Convert tree to Vnodes 785 (recursive create the vnode tree)
DOM ready 1196 (picodom.patch, requestAnimationFrame fired in a MutationObserver)
TOTAL TIME 2741.2550000000047

**Comment by leeoniya** [comment]
yeah, that's a lot. virtual dom in general is not well suited for enormous documents or stuff like syntax coloring that must generate tons of dom. pagination would be an obvious suggestion here, both for the browser (mch smaller dom) and the vdom lib (smaller vtree). you may get better results with projects like prosemiror [1] and mobiledoc [2].

[1] http://bustle.github.io/mobiledoc-kit/demo/
[2] https://prosemirror.net/

**Comment by cjh9** [comment]
@leeoniya Yes, but this is just a corner-case. The render time is fine especially since most of the work can be done in a web-worker. However, if I could do the diffing in another thread it would be awesome! When typing the dome-changeing is typically very small. Do you know of any other vdom implementation that can do diffing separately?

**Comment by leeoniya** [comment]
> Do you know of any other vdom implementation that can do diffing separately?

not off the top of my head, but definitely look through [1]. i dont think you will find any fast libs that can do this for the following reason: they patch iteratively rather than figuring out an "ideal" diff in advance and then applying it. i *suspect* that virtual-dom's patches are not the ideal dom-ops case in many situations that need complex reordering. i think you're on the right track by asking this question in petit-dom's repo, since it claims to implement the ideal diff/moves (as does ivi). however, looking at petit's code, it also does patching as part of the diffing process and may also be iterative to some extent.

[1] https://github.com/krausest/js-framework-benchmark

**Comment by JorgeBucaran** [comment]
@cjh9 You definitely need a strategy to work with large files. I think @leeoniya's paging idea is worth researching a bit.

Even if I tell you picodom will do what you want, it couldn't  possibly happen in just a few weeks, so you have ample time to explore other options.

I found this for you:

- https://github.com/snabbdom/snabbdom/issues/197

**Comment by cjh9** [comment]
@leeoniya I see, so the problem with MobileDoc is that it seems I can not render math. I want to do markdown+latex.. and to my knowledge Katex is the only fast option for the web right now.

I thought i was going to be able to do it with virtual-dom, but it turns out that the datastructures are typed. I have to do some kind of custom serializer (plain JSON won't work).
https://github.com/Matt-Esch/virtual-dom/blob/947ecf92b67d25bb693a0f625fa8e90c099887d5/vnode/is-vnode.js

@JorgeBucaran I'm afraid pagination won't work in this case. Everything would be fine if there was a virtual-dom library that could calculate the diff separately in a webworker and serialize it to plain JSON. The dom-patch will be tiny in a huge document like this if the algorithm is correct, because you usually just type in one character at a time.

Thank you for the link and the concern, I will continue look around.

**Comment by JorgeBucaran** [comment]
@cjh9 Cool! Thanks,

**Comment by mindplay-dk** [comment]
Possibly unrelated, but I noticed that `createElement` knows about `isSVG`, but `setAttribute` does not - and I've noticed some other libs use `setAttributeNS` when seting SVG attributes. Could this be for performance reasons? Just a thought.

**Comment by leeoniya** [comment]
@cjh9 i randomly stumbled upon this [1] today, which sounds like exactly what you're asking for.

[1] https://github.com/Gozala/dominion
