### ISSUE TITLE
Using styles as strings doesn't work

### ISSUE THREAD

**Issue by cjh9** [picodom/picodom#64]
So this `h('div', {style:'background:red;etc..'})` doesn't work styles are assumed to be an object.. Is it supposed to be like that or should we accept strings as well? Line 56 in `patch.js`

Also the NPM is pointing to an old version compared to the docs

```
const element = patch(
  parent,  // parent HTMLElement to be patched
  oldNode, // the old VNode
  newNode  // the new VNode
)
```

does't work, call signature has changed.

**Comment by JorgeBucaran** [comment]
@cjh9 Yes, `style` must be an object as you noted. See https://github.com/picodom/picodom/issues/25 for a previous discussion. 👋 

I'll update the docs, thanks!
