### ISSUE TITLE
Modularity

### ISSUE THREAD

**Issue by mindplay-dk** [picodom/picodom#81]
I'd like to propose we introduce a simple form of modularity.

This would allow us to delegate special handling of e.g. `style` and `class` to a separate module, and enables developers to extend and customize the engine via special attributes - for example, animation as well as integration with CSS-in-JS engines could be supported this way.

If we were to push `style` support to a module, for example, we could add more convenience features without bloating the main package - for example, deferred (next frame) style updates (for animations) etc. which require a few more lines of code, and it enables someone to replace `style` support with a custom implementation.

It also enables us to offer a standard solution for e.g. `class` support, which was previously [rejected](https://github.com/picodom/picodom/pull/55) as being outside the core scope of Picodom itself.

What I'd propose is a simple map of hooks for reserved attributes, for example via a new exported `mods` member, which would be a map where attribute-names map to a functions with the following signature:

    (element, oldNode, newNode) => void

So, for example, the current `style` behavior in module form might look like this:

```js
picodom.mods.style = function(element, oldNode, newNode) {
  var oldValue = oldNode.style || {}
  var newValue = newNode.style || {}

  for (var i in Object.assign({}, oldValue, newValue)) {
    element.style[i] = newValue[i] != null ? newValue[i] : ""
  }
}
```

The `patch` function would apply these functions *or* `setElementProp` as the default - in other words, modules *override* the `setElementProp` standard function, allowing for deeper customization and extension of the `patch` function than is possibly by proxying either it or the `h` function, and also avoiding the overhead of an extra function call per element when proxying `h`, and/or an additional full tree traversal required when proxying `patch`.

It should be pretty simple to implement, e.g. replace `setElementProps(...)` with `(mods[attrName] || setElementProps)(...)`, or possibly building it into `setElementProps` itself, if that performs better due to function inlining.

I'm not 100% sure about this idea, so feel free to criticize!

Thoughts?

**Comment by JorgeBucaran** [comment]
I think this is a great idea, but I am not interested in this for Picodom. I know this could be seen as narrow-minded, but I want Picodom to be a zero-option, drop-n-play minimum viable solution. 

Snabbdom has modules and a bunch of other customization options, check it out.

**Comment by mindplay-dk** [comment]
I understand why you want this to be drop-in and zero-configuration, but I'm not sure I understand why it's important to keep special handling of attributes under lock and bar?

I don't see the harm in *allowing* you to extend attribute-handling? As long as it's still "batteries included", in the sense that it's self-sufficient and ready to use without any additional setup.

I went ahead and tried it:

https://github.com/picodom/picodom/compare/master...mindplay-dk:modularity

In my opinion, this has some nice side-effects - I like how the special attributes are now organized at the top of the file, instead of having some handling scattered here and there. Check the commit log for other small side benefits.

I understand why you don't want things like [class map support](https://github.com/picodom/picodom/pull/55) in the main codebase, but this enables someone to plug that in really easily.

It's a net overhead of 10 bytes minified. (probably less with gzip.)
